### ISSUE TITLE
关于a的算法

### ISSUE THREAD

**Issue by Gesangs** [Monine/worklog#25]
想请教关于a的算法，如何推导而出

**Comment by Monine** [comment]
什么意思？麻烦描述清楚些。

**Comment by Gesangs** [comment]
在抛物线动画中，有个关于a的算法，有点看不明白
![1536805854109](https://user-images.githubusercontent.com/24218298/45463842-611ed280-b740-11e8-9c87-ae0764a37a89.jpg)
